# Tensors and Tensor Operations

In [1]:
import torch

## Tensor Creation

In [2]:
#create tensor
t = torch.Tensor(2,3)
print(t)

tensor([[2.5318e-12, 1.7034e+28, 1.8062e+28],
        [5.4214e-14, 4.7865e+22, 2.8826e+32]])


In [3]:
#or like this
t = torch.FloatTensor(2,3)
print(t)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
print(t.size())
print(t.dim())
print(len(t.size()) == t.dim())

torch.Size([2, 3])
2
True


In [9]:
#set values
t[0][0] = 1
t[0][1] = 2
t[0][2] = 3
t[1][0] = 4
t[1][1] = 5
t[1][2] = 6
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [11]:
#cast from float to int
t = torch.FloatTensor([1.1,2.2])
print(t)
t.type(torch.IntTensor)

tensor([1.1000, 2.2000])


tensor([1, 2], dtype=torch.int32)

In [13]:
#create tensor from tensor
t2 = torch.tensor(t)
print(t2)

C:\Users\Drake\Anaconda3\envs\Pytorch Deep Learning\lib\site-packages\ipykernel_launcher.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  """Entry point for launching an IPython kernel.


tensor([1.1000, 2.2000])


In [14]:
#from list
t3 = torch.IntTensor([[1,2],[3,4]])
print(t3)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [15]:
#from NumPy array
import numpy as np
a = np.array([55,66])
t4 = torch.Tensor(a)
print(t4)

tensor([55., 66.])


In [16]:
#Tensor with all zeros
t5 = torch.zeros(2,3)
print(t5)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [17]:
#All ones
t6 = torch.ones(2,3)
print(t6)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [18]:
#Tensor with all ones with Dim of another tensor
t7 = torch.ones_like(t4)
print(t7)

tensor([1., 1.])


## Tensor Operations

In [19]:
#Add two Tensors
t1 = torch.ones(2,2)
t2 = torch.ones(2,2)
t1+t2

tensor([[2., 2.],
        [2., 2.]])

In [20]:
t1.add(t2)
print(t1)

tensor([[1., 1.],
        [1., 1.]])


In [21]:
t1.add_(t2)
print(t1)

tensor([[2., 2.],
        [2., 2.]])


In [22]:
t1.cos()

tensor([[-0.4161, -0.4161],
        [-0.4161, -0.4161]])

In [23]:
torch.cos(t1)

tensor([[-0.4161, -0.4161],
        [-0.4161, -0.4161]])

In [24]:
#Create one-dim tensor of equally spaced points
torch.linspace(3,10, steps=5)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [26]:
#Create 1-D tensor with values from [start,end)
torch.arange(0,5)

tensor([0, 1, 2, 3, 4])

In [27]:
#Create tensor with random values from [0,1)
torch.rand((2,3))

tensor([[0.8753, 0.5927, 0.8142],
        [0.6336, 0.9622, 0.9058]])

In [28]:
#Create tensor with random values with normal distribution 
#with 0 mean and variance 1
torch.randn((2,3))

tensor([[-0.6692, -0.5189,  0.8160],
        [ 0.9871, -0.9365, -0.1536]])

In [29]:
#Matrix multiply
a = torch.rand((2,3))
b = torch.rand((3,2))

torch.mm(a,b)

tensor([[0.6264, 1.2650],
        [1.2114, 1.9192]])