# Variables

In [8]:
import torch
from torch.autograd import Variable

## Create Computation Graph

In [9]:
x = Variable(torch.FloatTensor([11.2]), requires_grad=True)
y = 2*x

In [10]:
print(x)
print(y)

tensor([11.2000], requires_grad=True)
tensor([22.4000], grad_fn=<MulBackward0>)


In [11]:
print(x.data)
print(y.data)

tensor([11.2000])
tensor([22.4000])


In [12]:
print(x.grad_fn)
print(y.grad_fn)

None


In [13]:
#calculate gradient
y.backward()

In [14]:
print(x.grad)
print(y.grad)

tensor([2.])
None
